import os
import unittest
from email import message_from_bytes

from fastpst.exporter import EmailExporter, cleanup_temp_files


class TestEmailExporter(unittest.TestCase):
    def tearDown(self):
        cleanup_temp_files()

    def test_create_eml_message(self):
        email_data = {
            "subject": "Test Status Meeting",
            "sender": "boss@work.com",
            "recipients": "dev@work.com",
            "date_sent": "2026-08-25 14:00:00",
            "plain_body": "Here is the plain message content.",
            "html_body": "<html><body><b>Here is the formatted HTML content.</b></body></html>",
        }
        attachments = [
            {"name": "notes.txt", "data": b"Meeting notes line 1\nline 2"}
        ]

        eml_msg = EmailExporter.create_eml_message(email_data, attachments)
        self.assertEqual(eml_msg["Subject"], "Test Status Meeting")
        self.assertEqual(eml_msg["From"], "boss@work.com")
        self.assertEqual(eml_msg["To"], "dev@work.com")

        # Parse generated bytes
        raw_bytes = eml_msg.as_bytes()
        parsed = message_from_bytes(raw_bytes)
        self.assertEqual(parsed["Subject"], "Test Status Meeting")

    def test_export_to_temp_eml(self):
        email_data = {
            "subject": "Temporary Email Test",
            "sender": "sender@test.com",
            "recipients": "receiver@test.com",
            "plain_body": "Testing temporary file export.",
        }
        temp_path = EmailExporter.export_to_temp_eml(email_data)
        self.assertTrue(os.path.exists(temp_path))
        self.assertTrue(temp_path.endswith(".eml"))

        # Verify cleanup
        cleanup_temp_files()
        self.assertFalse(os.path.exists(temp_path))


if __name__ == "__main__":
    unittest.main()
